Updated to Node.js v16 and v3 of actions
The previous setup caused an error. Example:
file:///Users/david/code/temp/gbfs-node/node_modules/csval/src/cli.js:11
  await readFile(new URL("../package.json", import.meta.url))
  ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)
    at async link (internal/modules/esm/module_job.js:42:21)